services:
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: lara

  web:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"